"""Homepage layouts; prose is source copy, except the explicitly requested UtterNow excerpt."""

def brandlogo():
    return '<span class="brand-art"><img class="brand-base" src="assets/exterprise-logo.png" alt="Exterprise — extend your enterprise" width="497" height="98"><img class="brand-lettering" src="assets/exterprise-logo.png" alt="" aria-hidden="true" width="497" height="98"></span>'

def hero(corporate, a, button, arrow):
    return '<section class="kinetic-hero" aria-labelledby="hero-heading"><canvas class="hero-wave" aria-hidden="true"></canvas><div class="kinetic-intro"><p>'+corporate['hero']['description']+'</p></div><div class="kinetic-heading"><h1 id="hero-heading">Extend your<br>Enterprise</h1><div class="kinetic-actions"><div class="hero-cta-group">'+button('#company-services','Solution &amp; Services Matrix')+a('servicenow.html','ServiceNow '+arrow,'kinetic-service')+'</div><a class="hero-discover" href="#partner"><span>Scroll to know more</span><span class="discover-arrow" aria-hidden="true">↓</span></a><button class="wave-toggle" type="button" aria-label="Pause background animation" aria-pressed="false" hidden><svg viewBox="0 0 24 24" aria-hidden="true"><path class="pause-icon" d="M9 6v12M15 6v12"/><path class="play-icon" d="m9 5 10 7-10 7z"/></svg></button></div></div><nav class="kinetic-links" aria-label="Explore Exterprise services">'+a('https://exterprise.us/outsourced-process/','Smartsourcing')+a('servicenow.html','ServiceNow')+a('https://exterprise.us/enterprise-solutions/','Enterprise')+a('https://exterprise.us/technical/','Technical')+'</nav></section><script src="hero-motion.js" defer></script>'

def brand_story(corporate, a, button, photo, arrow):
    h='<section class="brand-journey morph-journey" id="extend" aria-label="Design, Create &amp; Innovate"><div class="brand-pin"><div class="brand-track" aria-hidden="true"><span class="morph-word">Design,</span><span class="morph-pill"><span class="morph-icon">×</span></span><span class="morph-word morph-next">Create &amp;</span><span class="morph-word morph-last">Innovate.</span></div><div class="brand-statement"><h2>'+corporate['more'][1]['description']+'</h2>'+a(corporate['more'][1]['url'],'Design, Create &amp; Innovate '+arrow,'text-action')+'</div></div></section>'
    h+='<section class="red-capabilities" id="company-matrix"><div class="red-intro"><h2 data-reveal>Solution &amp; Services Matrix</h2><p>'+corporate['matrix_intro']+'</p>'+button('#company-services','Read more')+'</div><div class="red-card-stack">'
    for i,x in enumerate(corporate['matrix']):
        h+='<article class="red-service-card" style="--stack-order:'+str(i)+'"><span class="red-card-number" aria-hidden="true">'+str(i+1).zfill(2)+'</span>'+a(x['url'],'<h3>'+x['title']+'</h3><p>'+x['description']+'</p>'+photo(['network-servers','skyscraper-facade','team-computers'][i%3])+arrow)+'</article>'
    return h+'</div></section>'

def product(a, arrow):
    # User-supplied UtterNow promo; native YouTube controls include captions and fullscreen.
    return '<section class="utter-section utter-cinema" id="utternow" aria-labelledby="utter-title"><div class="utter-cinema-heading"><div><div class="utter-product-name">UtterNow</div><h2 id="utter-title">Your ServiceNow,<br>Now Voice-Activated</h2></div><div><p>Transform your ServiceNow workflows with natural voice commands. Create tickets, retrieve knowledge, and automate processes—all hands-free.</p>'+a('https://dev.utternow.ai/','Explore UtterNow '+arrow,'utter-link')+'</div></div><div class="utter-scroll-scene"><div class="utter-cinema-pin"><div class="utter-mosaic" aria-hidden="true"><img src="assets/gallery-service.png" alt="" loading="lazy" width="1536" height="1024"><img src="assets/gallery-data.png" alt="" loading="lazy" width="1536" height="1024"></div><div class="utter-cinema-film"><div class="utter-media"><iframe class="utter-youtube" src="https://www.youtube-nocookie.com/embed/oObUCT76Zj4?rel=0&amp;playsinline=1" title="UtterNow promotional video" loading="lazy" referrerpolicy="strict-origin-when-cross-origin" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share; fullscreen" allowfullscreen></iframe></div><a class="utter-video-source" href="https://www.youtube.com/watch?v=oObUCT76Zj4" target="_blank" rel="noopener noreferrer">Watch on YouTube '+arrow+'</a></div></div></div></section>'
